package com.ruoyi.remoting.crmInventorystock.wsdlfile;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2019-05-14T14:47:00.327+08:00
 * Generated source version: 3.0.1
 * 
 */
@WebService(targetNamespace = "http://www.example.org/QueryStockAgeFromIHSToB2B/", name = "QueryStockAgeFromIHSToB2B")
@XmlSeeAlso({ObjectFactory.class})
public interface QueryStockAgeFromIHSToB2B {

    @WebResult(name = "SelectStockAgeOutput", targetNamespace = "")
    @RequestWrapper(localName = "QueryStockAgeFromIHSToB2B", targetNamespace = "http://www.example.org/QueryStockAgeFromIHSToB2B/", className = "com.ruoyi.remoting.crmInventorystock.wsdlfile.QueryStockAgeFromIHSToB2B_Type")
    @WebMethod(operationName = "QueryStockAgeFromIHSToB2B", action = "http://www.example.org/QueryStockAgeFromIHSToB2B/QueryStockAgeFromIHSToB2B")
    @ResponseWrapper(localName = "QueryStockAgeFromIHSToB2BResponse", targetNamespace = "http://www.example.org/QueryStockAgeFromIHSToB2B/", className = "com.ruoyi.remoting.crmInventorystock.wsdlfile.QueryStockAgeFromIHSToB2BResponse")
    public java.util.List<com.ruoyi.remoting.crmInventorystock.wsdlfile.SelectStockAgeOutput> queryStockAgeFromIHSToB2B(
            @WebParam(name = "SaleCustCode", targetNamespace = "")
                    String saleCustCode,
            @WebParam(name = "MainCustType", targetNamespace = "")
                    String mainCustType,
            @WebParam(name = "Deptcode", targetNamespace = "")
                    String deptcode,
            @WebParam(name = "INVCODE", targetNamespace = "")
                    String invcode
    );
}
