
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.ruoyi.remoting.crmInventorystock.wsdlfile;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2019-05-14T14:47:00.309+08:00
 * Generated source version: 3.0.1
 * 
 */

@WebService(
                      serviceName = "QueryStockAgeFromIHSToB2B",
                      portName = "QueryStockAgeFromIHSToB2BSOAP",
                      targetNamespace = "http://www.example.org/QueryStockAgeFromIHSToB2B/",
                      wsdlLocation = "file:/E:/workspace-stu/demo_365/resource/wsdl/QueryStockAgeFromIHSToB2B.wsdl",
                      endpointInterface = "com.ruoyi.remoting.crmInventorystock.wsdlfile.QueryStockAgeFromIHSToB2B")
                      
public class QueryStockAgeFromIHSToB2BSOAPImpl implements QueryStockAgeFromIHSToB2B {

    private static final Logger LOG = Logger.getLogger(QueryStockAgeFromIHSToB2BSOAPImpl.class.getName());

    /* (non-Javadoc)
     * @see com.ruoyi.remoting.crmInventorystock.wsdlfile.QueryStockAgeFromIHSToB2B#queryStockAgeFromIHSToB2B(java.lang.String  saleCustCode ,)java.lang.String  mainCustType ,)java.lang.String  deptcode ,)java.lang.String  invcode )*
     */
    public java.util.List<com.ruoyi.remoting.crmInventorystock.wsdlfile.SelectStockAgeOutput> queryStockAgeFromIHSToB2B(String saleCustCode, String mainCustType, String deptcode, String invcode) {
        LOG.info("Executing operation queryStockAgeFromIHSToB2B");
        System.out.println(saleCustCode);
        System.out.println(mainCustType);
        System.out.println(deptcode);
        System.out.println(invcode);
        try {
            java.util.List<com.ruoyi.remoting.crmInventorystock.wsdlfile.SelectStockAgeOutput> _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
