
package com.ruoyi.remoting.crmInventorystock.wsdlfile;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2019-05-14T14:47:00.338+08:00
 * Generated source version: 3.0.1
 * 
 */
 
public class QueryStockAgeFromIHSToB2B_QueryStockAgeFromIHSToB2BSOAP_Server{

    protected QueryStockAgeFromIHSToB2B_QueryStockAgeFromIHSToB2BSOAP_Server() throws Exception {
        System.out.println("Starting Server");
        Object implementor = new QueryStockAgeFromIHSToB2BSOAPImpl();
        String address = "http://10.135.27.4:7001/EAI/RoutingProxyService/EAI_SOAP_ServiceRoot?INT_CODE=EAI_INT_2303";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws Exception {
        new QueryStockAgeFromIHSToB2B_QueryStockAgeFromIHSToB2BSOAP_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
