
package com.ruoyi.remoting.crmInventorystock.wsdlfile;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2019-05-14T14:47:00.278+08:00
 * Generated source version: 3.0.1
 * 
 */
public final class QueryStockAgeFromIHSToB2B_QueryStockAgeFromIHSToB2BSOAP_Client {

    private static final QName SERVICE_NAME = new QName("http://www.example.org/QueryStockAgeFromIHSToB2B/", "QueryStockAgeFromIHSToB2B");

    private QueryStockAgeFromIHSToB2B_QueryStockAgeFromIHSToB2BSOAP_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = QueryStockAgeFromIHSToB2B_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        QueryStockAgeFromIHSToB2B_Service ss = new QueryStockAgeFromIHSToB2B_Service(wsdlURL, SERVICE_NAME);
        QueryStockAgeFromIHSToB2B port = ss.getQueryStockAgeFromIHSToB2BSOAP();  
        
        {
        System.out.println("Invoking queryStockAgeFromIHSToB2B...");
        String _queryStockAgeFromIHSToB2B_saleCustCode = "";
        String _queryStockAgeFromIHSToB2B_mainCustType = "";
        String _queryStockAgeFromIHSToB2B_deptcode = "";
        String _queryStockAgeFromIHSToB2B_invcode = "";
        java.util.List<com.ruoyi.remoting.crmInventorystock.wsdlfile.SelectStockAgeOutput> _queryStockAgeFromIHSToB2B__return = port.queryStockAgeFromIHSToB2B(_queryStockAgeFromIHSToB2B_saleCustCode, _queryStockAgeFromIHSToB2B_mainCustType, _queryStockAgeFromIHSToB2B_deptcode, _queryStockAgeFromIHSToB2B_invcode);
        System.out.println("queryStockAgeFromIHSToB2B.result=" + _queryStockAgeFromIHSToB2B__return);


        }

        System.exit(0);
    }

}
